// CANVAS
const GAME_WINDOW_CANVAS_ID = "gameWindow";
const GAME_WINDOW_CANVAS_IMAGE_RENDERING = "pixelated";

// WINDOW
const GAME_WINDOW_SCALE = 3;
const GAME_WINDOW_WIDTH = 256;
const GAME_WINDOW_HEIGHT = 144;

// FONT
const GAME_FONT_NAME = "Press Start 2P";
const GAME_FONT_SIZE = 8;

// INPUT KEYS
const KEYDOWN_KEY = "keydown";
const GAME_START_KEY = "enter";

// STRING LITERALS
const START_GAME_TEXT = "START GAME";
const CREDITS_TEXT = "© JASON 2025";

// COLOR KEYS
const RED_COLOR = "#f00";
const BLACK_COLOR = "#000";
const ORANGE_COLOR = "#e09000";
const DARK_BLUE_COLOR = "#004";
const BRIGHT_RED_COLOR = "#b53120";
const BRIGHT_BLUE_COLOR = "#155fd9";
const PALE_YELLOW_COLOR = "#ffefaf";

// SPRITE FILENAMES
const GAME_LOGO_SPRITE_FILENAME = "assets/sprites/gameLogo.png";
const MAIN_MENU_CURSOR_SPRITE_FILENAME = "assets/sprites/mainMenuCursor.png";

// DURATIONS
const FADE_SCREEN_FADE_DURATION = 1;
const MAIN_MENU_CURSOR_MOVEMENT_TIME = 1;
const START_GAME_TEXT_UI_BLINK_DELAY = 1;
const START_GAME_TEXT_UI_BLINK_DELAY_ON_GAME_START = 0.03125;

// TEXT ALIGNMENT KEYS
const TEXT_ALIGNED_TO_LEFT_KEY = "left";
const TEXT_ALIGNED_TO_RIGHT_KEY = "right";
const TEXT_ALIGNED_TO_CENTER_KEY = "center";

// MISCELLANEOUS
const GAME_FPS = 60;
const PIXELS_UNIT = "px";
const MAIN_MENU_CURSOR_MOVEMENT_AMPLITUDE = 4;