class HighScoreIntCounterGroupUI extends IntCounterGroupUI {
	constructor() {
		super(HIGH_SCORE_HEADER_TEXT, new Point(GAME_WINDOW_WIDTH - SCORE_GROUP_UI_OFFSET_FROM_SCREEN_EDGES, SCORE_GROUP_UI_OFFSET_FROM_SCREEN_EDGES), TEXT_ALIGNED_TO_RIGHT_KEY);
	}
}