class PlayerScoreIntCounterGroupUI extends IntCounterGroupUI {
	constructor() {
		super(PLAYER_SCORE_HEADER_TEXT, new Point(SCORE_GROUP_UI_OFFSET_FROM_SCREEN_EDGES, SCORE_GROUP_UI_OFFSET_FROM_SCREEN_EDGES), TEXT_ALIGNED_TO_LEFT_KEY);
	}
}